# Generated by Django 5.2 on 2025-08-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0002_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='postvideo',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='blog_videos/'),
        ),
    ]
